'use client'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import { usePathname } from 'next/navigation'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
 const pathname = usePathname()
  const hideNavAndFooter = pathname === '/login'

  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable} w-full antialiased max-w-[1400px] mx-auto`}>
        {!hideNavAndFooter && <NavBar />}
        {children}
        {!hideNavAndFooter && <Footer />}
      </body>
    </html>
  )
}
